server:
 port: 8089

mybatis:
  mapper-locations: classpath:mybatis/*.xml,classpath:mybatis/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
     
spring:
   shardingsphere:
      datasource:
         names: dbt1,dbt2
         dbt1:
           type: com.zaxxer.hikari.HikariDataSource
           driverClassName: com.mysql.cj.jdbc.Driver
           jdbcUrl: jdbc:mysql://192.168.2.183:3306/dbt1?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
           username: root
           password: qwe123-=        
         dbt2:
           type: com.zaxxer.hikari.HikariDataSource
           driverClassName: com.mysql.cj.jdbc.Driver
           jdbcUrl: jdbc:mysql://192.168.2.183:3306/dbt2?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
           username: root
           password: qwe123-=
      sharding:
         tables:
            user:
               actualDataNodes: dbt1.user,dbt2.user
               databaseStrategy:
                  inline:
                     shardingColumn: tenant_id
                     algorithmExpression: dbt${tenant_id}