server:
 port: 8089

spring:
    rabbitmq:
        host: 172.16.10.45
        port: 31006
        username: admin
        password: qwe123-=
        listener:
          direct:
            acknowledge-mode: manual
          simple:
            acknowledge-mode: manual
