server:
 port: 8089

spring:
    rabbitmq:
        host: 172.16.200.53
        port: 5672
        username: admin
        password: qwe123-=
        virtual-host: /
        listener:
          direct:
            acknowledge-mode: manual
          simple:
            acknowledge-mode: manual
