server:
 port: 8088

spring:
    rabbitmq:
        host: 172.16.200.49
        port: 5672
        username: admin
        password: qwe123-=
        publisherConfirms: true
        listener:
          direct:
            acknowledge-mode: manual
          simple:
            acknowledge-mode: manual