server:
 port: 8088

spring:
    rabbitmq:
        host: 172.16.10.202
        port: 5672
        username: admin
        password: qwe123-=
        virtual-host: /
        listener:
          direct:
            acknowledge-mode: manual
          simple:
            acknowledge-mode: manual
