#端口          
server:
  port: 8101

spring:
  datasource:
    username: root
    password: qwe123-=
    url: jdbc:mysql://172.16.10.145:30017/db1?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.16.10.145
    port: 31012
    password: qwe123-=
  rabbitmq:
    host: 172.16.10.145
    port: 30001
    username: admin
    password: qwe123-=
    publisher-confirms: true #确认消息已发送到交换机(Exchange)
    publisher-returns: true #确认消息已发送到队列(Queue)
    listener:
      simple:
        acknowledge-mode: manual
#日志
logging:
  config: classpath:log4j2.xml

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sdstc.*.model
  configuration:
    #当查询数据为空时字段返回为null，不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true