server:
  port: 8089
spring:
  application:
    name: activiti7
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://172.16.200.49:3306/activiti?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: qwe123-=
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true   
    check-process-definitions: false