server:
 port: 8089

spring:
  datasource:
    url: jdbc:mysql://172.16.10.23:30017/flowable?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: qwe123-=
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

flowable:
  async-executor-activate: false