server:
 port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=yes&characterEncoding=UTF8&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
    username: root
    password: qwe123-=
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  quartz:
    job-store-type: jdbc
    jdbc:
       initialize-schema: NEVER