oauth2-server: http://localhost:8080

server:
  port: 8081

security:
  oauth2:
    client:
      client-id: client1
      client-secret: 111111
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key        
        
        
        
        
        
        
        
        
   