gateway-server: http://172.16.10.17:88

server:
  port: 8081

security:
  oauth2:
    client:
      client-id: client2
      client-secret: 111111
      access-token-uri: ${gateway-server}/oauth/token
      user-authorization-uri: ${gateway-server}/oauth/authorize
    resource:
      user-info-uri: ${gateway-server}/api/oauth2/user
      prefer-token-info: false
        
        
        
        
        
        
        
        
   