oauth2-server: http://192.168.2.183:8888/oauth2server

server:
  port: 8081

security:
  oauth2:
    client:
      client-id: client1
      client-secret: 111111
      access-token-uri: ${oauth2-server}/oauth/token
      user-authorization-uri: ${oauth2-server}/oauth/authorize
    resource:
      jwt:
        key-uri: ${oauth2-server}/oauth/token_key        
        
        
        
        
        
        
        
        
   